// SPDX-FileCopyrightText: 2026 Febris
// SPDX-License-Identifier: Apache-2.0
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Febris.EnumLibrary
{   
    //This language map meets RFC 5646 standard
    public enum LanguageMapTypeEnum
    {
        [Display(Name = "af")] af,
        [Display(Name = "af-ZA")] af_ZA,
        [Display(Name = "ar")] ar,
        [Display(Name = "ar-AE")] ar_AE,
        [Display(Name = "ar-BH")] ar_BH,
        [Display(Name = "ar-DZ")] ar_DZ,
        [Display(Name = "ar-EG")] ar_EG,
        [Display(Name = "ar-IQ")] ar_IQ,
        [Display(Name = "ar-JO")] ar_JO,
        [Display(Name = "ar-KW")] ar_KW,
        [Display(Name = "ar-LB")] ar_LB,
        [Display(Name = "ar-LY")] ar_LY,
        [Display(Name = "ar-MA")] ar_MA,
        [Display(Name = "ar-OM")] ar_OM,
        [Display(Name = "ar-QA")] ar_QA,
        [Display(Name = "ar-SA")] ar_SA,
        [Display(Name = "ar-SY")] ar_SY,
        [Display(Name = "ar-TN")] ar_TN,
        [Display(Name = "ar-YE")] ar_YE,
        [Display(Name = "az")] az,
        [Display(Name = "az-AZ")] az_AZ,
        [Display(Name = "az-Cyrl-AZ")] az_Cyrl_AZ,
        [Display(Name = "be")] be,
        [Display(Name = "be-BY")] be_BY,
        [Display(Name = "bg")] bg,
        [Display(Name = "bg-BG")] bg_BG,
        [Display(Name = "bs-BA")] bs_BA,
        [Display(Name = "ca")] ca,
        [Display(Name = "ca-ES")] ca_ES,
        [Display(Name = "cs")] cs,
        [Display(Name = "cs-CZ")] cs_CZ,
        [Display(Name = "cy")] cy,
        [Display(Name = "cy-GB")] cy_GB,
        [Display(Name = "da")] da,
        [Display(Name = "da-DK")] da_DK,
        [Display(Name = "de")] de,
        [Display(Name = "de-AT")] de_AT,
        [Display(Name = "de-CH")] de_CH,
        [Display(Name = "de-DE")] de_DE,
        [Display(Name = "de-LI")] de_LI,
        [Display(Name = "de-LU")] de_LU,
        [Display(Name = "dv")] dv,
        [Display(Name = "dv-MV")] dv_MV,
        [Display(Name = "el")] el,
        [Display(Name = "el-GR")] el_GR,
        [Display(Name = "en")] en,
        [Display(Name = "en-AU")] en_AU,
        [Display(Name = "en-BZ")] en_BZ,
        [Display(Name = "en-CA")] en_CA,
        [Display(Name = "en-CB")] en_CB,
        [Display(Name = "en-GB")] en_GB,
        [Display(Name = "en-IE")] en_IE,
        [Display(Name = "en-JM")] en_JM,
        [Display(Name = "en-NZ")] en_NZ,
        [Display(Name = "en-PH")] en_PH,
        [Display(Name = "en-TT")] en_TT,
        [Display(Name = "en-US")] en_US,
        [Display(Name = "en-ZA")] en_ZA,
        [Display(Name = "en-ZW")] en_ZW,
        [Display(Name = "eo")] eo,
        [Display(Name = "es")] es,
        [Display(Name = "es-AR")] es_AR,
        [Display(Name = "es-BO")] es_BO,
        [Display(Name = "es-CL")] es_CL,
        [Display(Name = "es-CO")] es_CO,
        [Display(Name = "es-CR")] es_CR,
        [Display(Name = "es-DO")] es_DO,
        [Display(Name = "es-EC")] es_EC,
        [Display(Name = "es-ES")] es_ES,
        [Display(Name = "es-GT")] es_GT,
        [Display(Name = "es-HN")] es_HN,
        [Display(Name = "es-MX")] es_MX,
        [Display(Name = "es-NI")] es_NI,
        [Display(Name = "es-PA")] es_PA,
        [Display(Name = "es-PE")] es_PE,
        [Display(Name = "es-PR")] es_PR,
        [Display(Name = "es-PY")] es_PY,
        [Display(Name = "es-SV")] es_SV,
        [Display(Name = "es-UY")] es_UY,
        [Display(Name = "es-VE")] es_VE,
        [Display(Name = "et")] et,
        [Display(Name = "et-EE")] et_EE,
        [Display(Name = "eu")] eu,
        [Display(Name = "eu-ES")] eu_ES,
        [Display(Name = "fa")] fa,
        [Display(Name = "fa-IR")] fa_IR,
        [Display(Name = "fi")] fi,
        [Display(Name = "fi-FI")] fi_FI,
        [Display(Name = "fo")] fo,
        [Display(Name = "fo-FO")] fo_FO,
        [Display(Name = "fr")] fr,
        [Display(Name = "fr-BE")] fr_BE,
        [Display(Name = "fr-CA")] fr_CA,
        [Display(Name = "fr-CH")] fr_CH,
        [Display(Name = "fr-FR")] fr_FR,
        [Display(Name = "fr-LU")] fr_LU,
        [Display(Name = "fr-MC")] fr_MC,
        [Display(Name = "gl")] gl,
        [Display(Name = "gl-ES")] gl_ES,
        [Display(Name = "gu")] gu,
        [Display(Name = "gu-IN")] gu_IN,
        [Display(Name = "he")] he,
        [Display(Name = "he-IL")] he_IL,
        [Display(Name = "hi")] hi,
        [Display(Name = "hi-IN")] hi_IN,
        [Display(Name = "hr")] hr,
        [Display(Name = "hr-BA")] hr_BA,
        [Display(Name = "hr-HR")] hr_HR,
        [Display(Name = "hu")] hu,
        [Display(Name = "hu-HU")] hu_HU,
        [Display(Name = "hy")] hy,
        [Display(Name = "hy-AM")] hy_AM,
        [Display(Name = "id")] id,
        [Display(Name = "id-ID")] id_ID,
        [Display(Name = "is")] is_lang,
        [Display(Name = "is-IS")] is_IS,
        [Display(Name = "it")] it,
        [Display(Name = "it-CH")] it_CH,
        [Display(Name = "it-IT")] it_IT,
        [Display(Name = "ja")] ja,
        [Display(Name = "ja-JP")] ja_JP,
        [Display(Name = "ka")] ka,
        [Display(Name = "ka-GE")] ka_GE,
        [Display(Name = "kk")] kk,
        [Display(Name = "kk-KZ")] kk_KZ,
        [Display(Name = "kn")] kn,
        [Display(Name = "kn-IN")] kn_IN,
        [Display(Name = "ko")] ko,
        [Display(Name = "ko-KR")] ko_KR,
        [Display(Name = "kok")] kok,
        [Display(Name = "kok-IN")] kok_IN,
        [Display(Name = "ky")] ky,
        [Display(Name = "ky-KG")] ky_KG,
        [Display(Name = "lt")] lt,
        [Display(Name = "lt-LT")] lt_LT,
        [Display(Name = "lv")] lv,
        [Display(Name = "lv-LV")] lv_LV,
        [Display(Name = "mi")] mi,
        [Display(Name = "mi-NZ")] mi_NZ,
        [Display(Name = "mk")] mk,
        [Display(Name = "mk-MK")] mk_MK,
        [Display(Name = "mn")] mn,
        [Display(Name = "mn-MN")] mn_MN,
        [Display(Name = "mr")] mr,
        [Display(Name = "mr-IN")] mr_IN,
        [Display(Name = "ms")] ms,
        [Display(Name = "ms-BN")] ms_BN,
        [Display(Name = "ms-MY")] ms_MY,
        [Display(Name = "mt")] mt,
        [Display(Name = "mt-MT")] mt_MT,
        [Display(Name = "nb")] nb,
        [Display(Name = "nb-NO")] nb_NO,
        [Display(Name = "nl")] nl,
        [Display(Name = "nl-BE")] nl_BE,
        [Display(Name = "nl-NL")] nl_NL,
        [Display(Name = "nn-NO")] nn_NO,
        [Display(Name = "ns")] ns,
        [Display(Name = "ns-ZA")] ns_ZA,
        [Display(Name = "pa")] pa,
        [Display(Name = "pa-IN")] pa_IN,
        [Display(Name = "pl")] pl,
        [Display(Name = "pl-PL")] pl_PL,
        [Display(Name = "ps")] ps,
        [Display(Name = "ps-AR")] ps_AR,
        [Display(Name = "pt")] pt,
        [Display(Name = "pt-BR")] pt_BR,
        [Display(Name = "pt-PT")] pt_PT,
        [Display(Name = "qu")] qu,
        [Display(Name = "qu-BO")] qu_BO,
        [Display(Name = "qu-EC")] qu_EC,
        [Display(Name = "qu-PE")] qu_PE,
        [Display(Name = "ro")] ro,
        [Display(Name = "ro-RO")] ro_RO,
        [Display(Name = "ru")] ru,
        [Display(Name = "ru-RU")] ru_RU,
        [Display(Name = "sa")] sa,
        [Display(Name = "sa-IN")] sa_IN,
        [Display(Name = "se")] se,
        [Display(Name = "se-FI")] se_FI,
        [Display(Name = "se-NO")] se_NO,
        [Display(Name = "se-SE")] se_SE,
        [Display(Name = "sk")] sk,
        [Display(Name = "sk-SK")] sk_SK,
        [Display(Name = "sl")] sl,
        [Display(Name = "sl-SI")] sl_SI,
        [Display(Name = "sq")] sq,
        [Display(Name = "sq-AL")] sq_AL,
        [Display(Name = "sr-BA")] sr_BA,
        [Display(Name = "sr-Cyrl-BA")] sr_Cyrl_BA,
        [Display(Name = "sr-SP")] sr_SP,
        [Display(Name = "sr-Cyrl-SP")] sr_Cyrl_SP,
        [Display(Name = "sv")] sv,
        [Display(Name = "sv-FI")] sv_FI,
        [Display(Name = "sv-SE")] sv_SE,
        [Display(Name = "sw")] sw,
        [Display(Name = "sw-KE")] sw_KE,
        [Display(Name = "syr")] syr,
        [Display(Name = "syr-SY")] syr_SY,
        [Display(Name = "ta")] ta,
        [Display(Name = "ta-IN")] ta_IN,
        [Display(Name = "te")] te,
        [Display(Name = "te-IN")] te_IN,
        [Display(Name = "th")] th,
        [Display(Name = "th-TH")] th_TH,
        [Display(Name = "tl")] tl,
        [Display(Name = "tl-PH")] tl_PH,
        [Display(Name = "tn")] tn,
        [Display(Name = "tn-ZA")] tn_ZA,
        [Display(Name = "tr")] tr,
        [Display(Name = "tr-TR")] tr_TR,
        [Display(Name = "tt")] tt,
        [Display(Name = "tt-RU")] tt_RU,
        [Display(Name = "ts")] ts,
        [Display(Name = "uk")] uk,
        [Display(Name = "uk-UA")] uk_UA,
        [Display(Name = "ur")] ur,
        [Display(Name = "ur-PK")] ur_PK,
        [Display(Name = "uz")] uz,
        [Display(Name = "uz-UZ")] uz_UZ,
        [Display(Name = "uz-Cyrl-UZ")] uz_Cyrl_UZ,
        [Display(Name = "vi")] vi,
        [Display(Name = "vi-VN")] vi_VN,
        [Display(Name = "xh")] xh,
        [Display(Name = "xh-ZA")] xh_ZA,
        [Display(Name = "zh")] zh,
        [Display(Name = "zh-CN")] zh_CN,
        [Display(Name = "zh-HK")] zh_HK,
        [Display(Name = "zh-MO")] zh_MO,
        [Display(Name = "zh-SG")] zh_SG,
        [Display(Name = "zh-TW")] zh_TW,
        [Display(Name = "zu")] zu,
        [Display(Name = "zu-ZA")] zu_ZA,
        //[Display(Name = "af")] af = 0,
        //[Display(Name = "af-ZA")] af_ZA = 1,
        //[Display(Name = "ar")] ar = 2,
        //[Display(Name = "ar-AE")] ar_AE = 3,
        //[Display(Name = "ar-BH")] ar_BH = 4,
        //[Display(Name = "ar-DZ")] ar_DZ = 5,
        //[Display(Name = "ar-EG")] ar_EG = 6,
        //[Display(Name = "ar-IQ")] ar_IQ = 7,
        //[Display(Name = "ar-JO")] ar_JO = 8,
        //[Display(Name = "ar-KW")] ar_KW = 9,
        //[Display(Name = "ar-LB")] ar_LB = 10,
        //[Display(Name = "ar-LY")] ar_LY = 11,
        //[Display(Name = "ar-MA")] ar_MA = 12,
        //[Display(Name = "ar-OM")] ar_OM = 13,
        //[Display(Name = "ar-QA")] ar_QA = 14,
        //[Display(Name = "ar-SA")] ar_SA = 15,
        //[Display(Name = "ar-SY")] ar_SY = 16,
        //[Display(Name = "ar-TN")] ar_TN = 17,
        //[Display(Name = "ar-YE")] ar_YE = 18,
        //[Display(Name = "az")] az = 19,
        //[Display(Name = "az-AZ")] az_AZ = 20,
        //[Display(Name = "az-Cyrl-AZ")] az_Cyrl_AZ = 21,
        //[Display(Name = "be")] be = 22,
        //[Display(Name = "be-BY")] be_BY = 23,
        //[Display(Name = "bg")] bg = 24,
        //[Display(Name = "bg-BG")] bg_BG = 25,
        //[Display(Name = "bs-BA")] bs_BA = 26,
        //[Display(Name = "ca")] ca = 27,
        //[Display(Name = "ca-ES")] ca_ES = 28,
        //[Display(Name = "cs")] cs = 29,
        //[Display(Name = "cs-CZ")] cs_CZ = 30,
        //[Display(Name = "cy")] cy = 31,
        //[Display(Name = "cy-GB")] cy_GB = 32,
        //[Display(Name = "da")] da = 33,
        //[Display(Name = "da-DK")] da_DK = 34,
        //[Display(Name = "de")] de = 35,
        //[Display(Name = "de-AT")] de_AT = 36,
        //[Display(Name = "de-CH")] de_CH = 37,
        //[Display(Name = "de-DE")] de_DE = 38,
        //[Display(Name = "de-LI")] de_LI = 39,
        //[Display(Name = "de-LU")] de_LU = 40,
        //[Display(Name = "dv")] dv = 41,
        //[Display(Name = "dv-MV")] dv_MV = 42,
        //[Display(Name = "el")] el = 43,
        //[Display(Name = "el-GR")] el_GR = 44,
        //[Display(Name = "en")] en = 45,
        //[Display(Name = "en-AU")] en_AU = 46,
        //[Display(Name = "en-BZ")] en_BZ = 47,
        //[Display(Name = "en-CA")] en_CA = 48,
        //[Display(Name = "en-CB")] en_CB = 49,
        //[Display(Name = "en-GB")] en_GB = 50,
        //[Display(Name = "en-IE")] en_IE = 51,
        //[Display(Name = "en-JM")] en_JM = 52,
        //[Display(Name = "en-NZ")] en_NZ = 53,
        //[Display(Name = "en-PH")] en_PH = 54,
        //[Display(Name = "en-TT")] en_TT = 55,
        //[Display(Name = "en-US")] en_US = 56,
        //[Display(Name = "en-ZA")] en_ZA = 57,
        //[Display(Name = "en-ZW")] en_ZW = 58,
        //[Display(Name = "eo")] eo = 59,
        //[Display(Name = "es")] es = 60,
        //[Display(Name = "es-AR")] es_AR = 61,
        //[Display(Name = "es-BO")] es_BO = 62,
        //[Display(Name = "es-CL")] es_CL = 63,
        //[Display(Name = "es-CO")] es_CO = 64,
        //[Display(Name = "es-CR")] es_CR = 65,
        //[Display(Name = "es-DO")] es_DO = 66,
        //[Display(Name = "es-EC")] es_EC = 67,
        //[Display(Name = "es-ES")] es_ES = 68,
        //[Display(Name = "es-GT")] es_GT = 69,
        //[Display(Name = "es-HN")] es_HN = 70,
        //[Display(Name = "es-MX")] es_MX = 71,
        //[Display(Name = "es-NI")] es_NI = 72,
        //[Display(Name = "es-PA")] es_PA = 73,
        //[Display(Name = "es-PE")] es_PE = 74,
        //[Display(Name = "es-PR")] es_PR = 75,
        //[Display(Name = "es-PY")] es_PY = 76,
        //[Display(Name = "es-SV")] es_SV = 77,
        //[Display(Name = "es-UY")] es_UY = 78,
        //[Display(Name = "es-VE")] es_VE = 79,
        //[Display(Name = "et")] et = 80,
        //[Display(Name = "et-EE")] et_EE = 81,
        //[Display(Name = "eu")] eu = 82,
        //[Display(Name = "eu-ES")] eu_ES = 83,
        //[Display(Name = "fa")] fa = 84,
        //[Display(Name = "fa-IR")] fa_IR = 85,
        //[Display(Name = "fi")] fi = 86,
        //[Display(Name = "fi-FI")] fi_FI = 87,
        //[Display(Name = "fo")] fo = 88,
        //[Display(Name = "fo-FO")] fo_FO = 89,
        //[Display(Name = "fr")] fr = 90,
        //[Display(Name = "fr-BE")] fr_BE = 91,
        //[Display(Name = "fr-CA")] fr_CA = 92,
        //[Display(Name = "fr-CH")] fr_CH = 93,
        //[Display(Name = "fr-FR")] fr_FR = 94,
        //[Display(Name = "fr-LU")] fr_LU = 95,
        //[Display(Name = "fr-MC")] fr_MC = 96,
        //[Display(Name = "gl")] gl = 97,
        //[Display(Name = "gl-ES")] gl_ES = 98,
        //[Display(Name = "gu")] gu = 99,
        //[Display(Name = "gu-IN")] gu_IN = 100,
        //[Display(Name = "he")] he = 101,
        //[Display(Name = "he-IL")] he_IL = 102,
        //[Display(Name = "hi")] hi = 103,
        //[Display(Name = "hi-IN")] hi_IN = 104,
        //[Display(Name = "hr")] hr = 105,
        //[Display(Name = "hr-BA")] hr_BA = 106,
        //[Display(Name = "hr-HR")] hr_HR = 107,
        //[Display(Name = "hu")] hu = 108,
        //[Display(Name = "hu-HU")] hu_HU = 109,
        //[Display(Name = "hy")] hy = 110,
        //[Display(Name = "hy-AM")] hy_AM = 111,
        //[Display(Name = "id")] id = 112,
        //[Display(Name = "id-ID")] id_ID = 113,
        ////[Display(Name = "is")]is = 114,
        //[Display(Name = "is-IS")] is_IS = 115,
        //[Display(Name = "it")] it = 116,
        //[Display(Name = "it-CH")] it_CH = 117,
        //[Display(Name = "it-IT")] it_IT = 118,
        //[Display(Name = "ja")] ja = 119,
        //[Display(Name = "ja-JP")] ja_JP = 120,
        //[Display(Name = "ka")] ka = 121,
        //[Display(Name = "ka-GE")] ka_GE = 122,
        //[Display(Name = "kk")] kk = 123,
        //[Display(Name = "kk-KZ")] kk_KZ = 124,
        //[Display(Name = "kn")] kn = 125,
        //[Display(Name = "kn-IN")] kn_IN = 126,
        //[Display(Name = "ko")] ko = 127,
        //[Display(Name = "ko-KR")] ko_KR = 128,
        //[Display(Name = "kok")] kok = 129,
        //[Display(Name = "kok-IN")] kok_IN = 130,
        //[Display(Name = "ky")] ky = 131,
        //[Display(Name = "ky-KG")] ky_KG = 132,
        //[Display(Name = "lt")] lt = 133,
        //[Display(Name = "lt-LT")] lt_LT = 134,
        //[Display(Name = "lv")] lv = 135,
        //[Display(Name = "lv-LV")] lv_LV = 136,
        //[Display(Name = "mi")] mi = 137,
        //[Display(Name = "mi-NZ")] mi_NZ = 138,
        //[Display(Name = "mk")] mk = 139,
        //[Display(Name = "mk-MK")] mk_MK = 140,
        //[Display(Name = "mn")] mn = 141,
        //[Display(Name = "mn-MN")] mn_MN = 142,
        //[Display(Name = "mr")] mr = 143,
        //[Display(Name = "mr-IN")] mr_IN = 144,
        //[Display(Name = "ms")] ms = 145,
        //[Display(Name = "ms-BN")] ms_BN = 146,
        //[Display(Name = "ms-MY")] ms_MY = 147,
        //[Display(Name = "mt")] mt = 148,
        //[Display(Name = "mt-MT")] mt_MT = 149,
        //[Display(Name = "nb")] nb = 150,
        //[Display(Name = "nb-NO")] nb_NO = 151,
        //[Display(Name = "nl")] nl = 152,
        //[Display(Name = "nl-BE")] nl_BE = 153,
        //[Display(Name = "nl-NL")] nl_NL = 154,
        //[Display(Name = "nn-NO")] nn_NO = 155,
        //[Display(Name = "ns")] ns = 156,
        //[Display(Name = "ns-ZA")] ns_ZA = 157,
        //[Display(Name = "pa")] pa = 158,
        //[Display(Name = "pa-IN")] pa_IN = 159,
        //[Display(Name = "pl")] pl = 160,
        //[Display(Name = "pl-PL")] pl_PL = 161,
        //[Display(Name = "ps")] ps = 162,
        //[Display(Name = "ps-AR")] ps_AR = 163,
        //[Display(Name = "pt")] pt = 164,
        //[Display(Name = "pt-BR")] pt_BR = 165,
        //[Display(Name = "pt-PT")] pt_PT = 166,
        //[Display(Name = "qu")] qu = 167,
        //[Display(Name = "qu-BO")] qu_BO = 168,
        //[Display(Name = "qu-EC")] qu_EC = 169,
        //[Display(Name = "qu-PE")] qu_PE = 170,
        //[Display(Name = "ro")] ro = 171,
        //[Display(Name = "ro-RO")] ro_RO = 172,
        //[Display(Name = "ru")] ru = 173,
        //[Display(Name = "ru-RU")] ru_RU = 174,
        //[Display(Name = "sa")] sa = 175,
        //[Display(Name = "sa-IN")] sa_IN = 176,
        //[Display(Name = "se")] se = 177,
        //[Display(Name = "se-FI")] se_FI = 178,
        //[Display(Name = "se-NO")] se_NO = 179,
        //[Display(Name = "se-SE")] se_SE = 180,
        //[Display(Name = "sk")] sk = 181,
        //[Display(Name = "sk-SK")] sk_SK = 182,
        //[Display(Name = "sl")] sl = 183,
        //[Display(Name = "sl-SI")] sl_SI = 184,
        //[Display(Name = "sq")] sq = 185,
        //[Display(Name = "sq-AL")] sq_AL = 186,
        //[Display(Name = "sr-BA")] sr_BA = 187,
        //[Display(Name = "sr-Cyrl-BA")] sr_Cyrl_BA = 188,
        //[Display(Name = "sr-SP")] sr_SP = 189,
        //[Display(Name = "sr-Cyrl-SP")] sr_Cyrl_SP = 190,
        //[Display(Name = "sv")] sv = 191,
        //[Display(Name = "sv-FI")] sv_FI = 192,
        //[Display(Name = "sv-SE")] sv_SE = 193,
        //[Display(Name = "sw")] sw = 194,
        //[Display(Name = "sw-KE")] sw_KE = 195,
        //[Display(Name = "syr")] syr = 196,
        //[Display(Name = "syr-SY")] syr_SY = 197,
        //[Display(Name = "ta")] ta = 198,
        //[Display(Name = "ta-IN")] ta_IN = 199,
        //[Display(Name = "te")] te = 200,
        //[Display(Name = "te-IN")] te_IN = 201,
        //[Display(Name = "th")] th = 202,
        //[Display(Name = "th-TH")] th_TH = 203,
        //[Display(Name = "tl")] tl = 204,
        //[Display(Name = "tl-PH")] tl_PH = 205,
        //[Display(Name = "tn")] tn = 206,
        //[Display(Name = "tn-ZA")] tn_ZA = 207,
        //[Display(Name = "tr")] tr = 208,
        //[Display(Name = "tr-TR")] tr_TR = 209,
        //[Display(Name = "tt")] tt = 210,
        //[Display(Name = "tt-RU")] tt_RU = 211,
        //[Display(Name = "ts")] ts = 212,
        //[Display(Name = "uk")] uk = 213,
        //[Display(Name = "uk-UA")] uk_UA = 214,
        //[Display(Name = "ur")] ur = 215,
        //[Display(Name = "ur-PK")] ur_PK = 216,
        //[Display(Name = "uz")] uz = 217,
        //[Display(Name = "uz-UZ")] uz_UZ = 218,
        //[Display(Name = "uz-Cyrl-UZ")] uz_Cyrl_UZ = 219,
        //[Display(Name = "vi")] vi = 220,
        //[Display(Name = "vi-VN")] vi_VN = 221,
        //[Display(Name = "xh")] xh = 222,
        //[Display(Name = "xh-ZA")] xh_ZA = 223,
        //[Display(Name = "zh")] zh = 224,
        //[Display(Name = "zh-CN")] zh_CN = 225,
        //[Display(Name = "zh-HK")] zh_HK = 226,
        //[Display(Name = "zh-MO")] zh_MO = 227,
        //[Display(Name = "zh-SG")] zh_SG = 228,
        //[Display(Name = "zh-TW")] zh_TW = 229,
        //[Display(Name = "zu")] zu = 230,
        //[Display(Name = "zu-ZA")] zu_ZA = 231,
    }   
}
